### ISSUE TITLE
Find `soymilk` and `soy milk` via ingredient search

### ISSUE THREAD

**Issue by queencitra** [openculinary/knowledge-graph#21]
there are 2 soymilk (soy milk and soymilk), it should refer to same thing

**Comment by jayaddison** [comment]
It should be possible to handle this using [ingredient canonicalizations](https://github.com/openculinary/knowledge-graph/blob/f1075b05a3c4e62c6f141ea876126738a0bd8310/web/data/canonicalizations.txt).

**Comment by jayaddison** [comment]
Following some discussion about whether `soymilk` or `soy milk` should be the canonical representation, it has been determined that `soy milk` is the best representation for now.

This would allow users to search for recipes containing `milk` and to potentially see results that use `soy milk` (often a reasonable substitute).

In addition, it preserves information about the process involved in creating the ingredient - it is `milk` produced from `soy`.

**Comment by jayaddison** [comment]
Recipes require reindexing for the fix from #25 to take effect; I'm going to re-open this issue until it is fully resolved.

**Comment by jayaddison** [comment]
This is now resolved; :wave: goodbye, `soymilk`, :wave: hello, `soy milk`.
